### PR TITLE
Enable dynamic_terrain for europa_test_dem

### PR DESCRIPTION
**Pull request by Samahu**
## Summary of Chnages
Enable the dynamic_terrain plugin for europa_test_dem

## Test
Launch the simulation using
```bash
roslaunch ow europa_test_dem.launch
```
Test terrain deformation using any of the following activities
* dig_linear
* dig_circular
* grind

### CODE REVIEW

**Comment by kmdalal** [comment]
Still testing, but so far no luck:
- dig_circular didn't work because of the RRTCONNECT problem; the dig was high off the ground
- grind didn't reveal any deformation as used in ReferenceMission1.  The following error appeared at each pass:
```
[ERROR]: Controller is taking too long to execute trajectory (the expected upper bound for the trajectory execution was 1.565772 seconds). Stopping trajectory.
[ INFO]: Cancelling execution for grinder_controller
[ INFO]: Completed trajectory execution with status TIMED_OUT ...
[ INFO]: Controller grinder_controller successfully finished
[ INFO]: ABORTED: Timeout reached
[ INFO]: Received event 'stop'
```

**Comment by Samahu** [comment]
> Still testing, but so far no luck:
> 
> * dig_circular didn't work because of the RRTCONNECT problem; the dig was high off the ground
> * grind didn't reveal any deformation as used in ReferenceMission1.  The following error appeared at each pass:
> 
> ```
> [ERROR]: Controller is taking too long to execute trajectory (the expected upper bound for the trajectory execution was 1.565772 seconds). Stopping trajectory.
> [ INFO]: Cancelling execution for grinder_controller
> [ INFO]: Completed trajectory execution with status TIMED_OUT ...
> [ INFO]: Controller grinder_controller successfully finished
> [ INFO]: ABORTED: Timeout reached
> [ INFO]: Received event 'stop'
> ```

The dig_circular issue out of scope for this ticket.
With regard to the terrain not deforming using the grind this is due to the fact we limit the effect of the grinder to 1/3 of its size. So to see the result of it you need to disable **use_defaults** when performing dig_circular and also set the depth to a larger value.

**Comment by kmdalal** [comment]
I've made over 20 attempts with grind() and still do not see any terrain deformation.  Here's one that seems should work:

rosservice call -- /arm/grind false 2 0 0.35 0.3 false 0

The grinder seems to go underground deep enough but there is no visual effect - why?  Can someone provide an example call to grind() that does?

**Comment by Samahu** [comment]
> I've made over 20 attempts with grind() and still do not see any terrain deformation. Here's one that seems should work:
> 
> rosservice call -- /arm/grind false 2 0 0.35 0.3 false 0
> 
> The grinder seems to go underground deep enough but there is no visual effect - why? Can someone provide an example call to grind() that does?

Interesting .. I haven't tested the grind operation specifically. Let me look in depth into this.

**Comment by Samahu** [comment]
@kmdalal I did test the grind operation and I don't think dynamic_terrain plugin would work for this scenario. The reason is because the terrain where the lander sits has slope which thus the lander is a bit tilted. In turn the grinder is tilted. The dynamic_terrain grind deformation has been limited to only affect the terrain if it closely perpendicular to the xy plane. Thus since the grinder is tilted the operation is set not to alter the terrain. I need to re-work multiple things within the dynamic_terrain plugin to support this.

**Comment by Samahu** [comment]
@kmdalal In conclusion, I suggest we merge this and work on supporting the grinder terrain deformation on next release

**Review by damianacatanoso — APPROVED** [review]

**Pull request merged**
