### PR TITLE
Use the same shader for all worlds.

### PR DESCRIPTION
**Pull request by mogumbo**
This world should look the same as before:
`roslaunch ow atacama_y1a.launch`

These worlds have lost their medium resolution detail normal map, so they should look smoother than before:
`roslaunch ow europa_terminator.launch`
`roslaunch ow europa_terminator_workspace.launch`
`roslaunch ow europa_test_dem.launch`

### CODE REVIEW

**Comment by AstroStucky** [comment]
This may be unrelated to this PR, but I'm seeing an anomaly in the lander light projection.
default_gzclient_camera(1)-2023-05-24T11_11_02 799043

And you can see how the anomaly moves as the spotlights move in this video

https://github.com/nasa/ow_europa/assets/17039973/cd4a3b4c-6dc2-4097-a7fe-585b0e906dba

I say it could be unrelated because I imagine it was much harder to see when the terrain had more detail, lending credibility to your point that these worlds work better as test terrains with less detail.

**Review by AstroStucky — APPROVED** [review]
All 4 worlds look as described. I feel conflicted about making these 3 worlds look lower fidelity, but I can also understand the reason behind it. It might be worth getting feedback from the users. It is very possible nobody is even using these worlds for vision tests.

**Comment by mogumbo** [comment]
> I say it could be unrelated because I imagine it was much harder to see when the terrain had more detail, lending credibility to your point that these worlds work better as test terrains with less detail.

Good eye. I have seen that before but not in a way that interfered with any of our images. So simplifying the appearance of these worlds is already helping us see existing problems.

As far as I know, this problem is due to an Ogre bug. For VIPER we added a workaround to Ogre's code, but that's not an option for us at the moment on OceanWATERS. It would require us to use a custom Ogre build.

**Comment by AstroStucky** [comment]
It would be good to have a Jira ticket for the problem. Is the Ogre bug reported on somewhere online?

**Pull request merged**
